### ISSUE TITLE
Amethyst texture for both quicksand and redquicksand

### ISSUE THREAD

**Issue by Cadichon** [RaymondBlaze/quicksand-forge#1]
Quicksand and redquicksand both have wrong texture. They are using the Amethyst texture.
Forge : 43.1.47 and 43.1.1
Quicksand-forge : 1.3.0

See texture [here](https://imgur.com/a/uE33kj0)

**Comment by RaymondBlaze** [comment]
God I forgot to change the test texture back XD
Thanks for noticing :)
