### ISSUE TITLE
Incompatibility with Do a Barrel Roll

### ISSUE THREAD

**Issue by nitbe** [RaymondBlaze/quicksand-forge#2]
[minecraft-exported-crash-info-2022-11-13T10-11-31.zip](https://github.com/ChannelingMC/quicksand-forge/files/10019256/minecraft-exported-crash-info-2022-11-13T10-11-31.zip)

**Comment by RaymondBlaze** [comment]
This is actually a problem on [Do a Barrel Roll](https://github.com/enjarai/do-a-barrel-roll)'s side.

They're shading MixinExtras into their mod jar but not relocating it, which is a bad choice.

See MixinExtras' statement about this: https://github.com/LlamaLad7/MixinExtras#bundling-mixinextras

Quicksand (Forge) is using Forge's Jar-in-Jar for best compatibility, I'll open an issue for Do a Barrel Roll and suggest them to move to Jar-in-Jar or relocated shadow jar.

**Comment by ZekerZhayard** [comment]
![image](https://user-images.githubusercontent.com/41327811/202238066-72b12c4f-851e-45b3-9006-ad16f315e9de.png)
![image](https://user-images.githubusercontent.com/41327811/202238329-6ceabae7-e870-4f91-97c9-b1b85d4b389f.png)

**Comment by RaymondBlaze** [comment]
Additional note from Do a Barrel Roll: This has been fixed a month ago since it's 2.0.3 version

**Comment by nitbe** [comment]
> ![图片](https://user-images.githubusercontent.com/41327811/202238066-72b12c4f-851e-45b3-9006-ad16f315e9de.png) ![图片](https://user-images.githubusercontent.com/41327811/202238329-6ceabae7-e870-4f91-97c9-b1b85d4b389f.png)

草 我说我怎么找不到jar in jar
